// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearSessions() {
  return window['go']['main']['App']['ClearSessions']();
}

export function ClearUpstreamProxy() {
  return window['go']['main']['App']['ClearUpstreamProxy']();
}

export function CopyCertificateURL() {
  return window['go']['main']['App']['CopyCertificateURL']();
}

export function CopyProxyAddress() {
  return window['go']['main']['App']['CopyProxyAddress']();
}

export function DisableSystemProxy() {
  return window['go']['main']['App']['DisableSystemProxy']();
}

export function EnableSystemProxy() {
  return window['go']['main']['App']['EnableSystemProxy']();
}

export function ExportHAR() {
  return window['go']['main']['App']['ExportHAR']();
}

export function GetSession(arg1) {
  return window['go']['main']['App']['GetSession'](arg1);
}

export function GetSessions() {
  return window['go']['main']['App']['GetSessions']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function InstallRootCertificate() {
  return window['go']['main']['App']['InstallRootCertificate']();
}

export function OpenCertificateLocation() {
  return window['go']['main']['App']['OpenCertificateLocation']();
}

export function OpenCertificateURL() {
  return window['go']['main']['App']['OpenCertificateURL']();
}

export function OpenPathLocation(arg1) {
  return window['go']['main']['App']['OpenPathLocation'](arg1);
}

export function SetHTTPSIntercept(arg1) {
  return window['go']['main']['App']['SetHTTPSIntercept'](arg1);
}

export function SetUpstreamProxy(arg1) {
  return window['go']['main']['App']['SetUpstreamProxy'](arg1);
}

export function StartProxy() {
  return window['go']['main']['App']['StartProxy']();
}

export function StopProxy() {
  return window['go']['main']['App']['StopProxy']();
}
