// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {capture} from '../models';
import {main} from '../models';

export function AllowMobileFirewallAccess():Promise<void>;

export function ClearSessions():Promise<void>;

export function ClearUpstreamProxy():Promise<void>;

export function CopyCertificateURL():Promise<void>;

export function CopyProxyAddress():Promise<void>;

export function DisableSystemProxy():Promise<void>;

export function EnableSystemProxy():Promise<void>;

export function ExportHAR():Promise<string>;

export function GetSession(arg1:string):Promise<capture.SessionDetail>;

export function GetSessions():Promise<Array<capture.SessionSummary>>;

export function GetStatus():Promise<main.Status>;

export function InstallRootCertificate():Promise<void>;

export function OpenCertificateLocation():Promise<void>;

export function OpenCertificateURL():Promise<void>;

export function OpenPathLocation(arg1:string):Promise<void>;

export function SetHTTPSIntercept(arg1:boolean):Promise<void>;

export function SetUpstreamProxy(arg1:string):Promise<void>;

export function StartProxy():Promise<void>;

export function StopProxy():Promise<void>;
